// The square pool. APPEND ONLY: shared links store card squares by index,
// so reordering or deleting entries would scramble cards people already sent.
// To retire a square, add its index to RETIRED instead of removing it.
window.BINGO = {
  FREE_SPACE: "AI posts (FREE SPACE)",

  // Indices 0 to 7 are the original graphic, in reading order.
  CLASSIC: [0, 1, 2, 3, 4, 5, 6, 7],

  RETIRED: [],

  SQUARES: [
    "Someone announcing LinkedIn has never been better",
    "AI comments",
    "LinkedIn testing something that doesn't work",
    "Humble bragging",
    "Someone announcing LinkedIn is dead",
    "Someone announcing LinkedIn is cringe",
    "Being pitch slapped",
    "The announcement of a new cohort",
    "A post ending with \"Agree?\"",
    "\"I'm thrilled to announce...\"",
    "Broetry. One line. At a time.",
    "\"Great insights!\" comments",
    "Commenting \"Interested\" on a job post",
    "A B2B lesson from a toddler",
    "A post full of em dashes",
    "🚀 Emoji 🚀 bullet 🚀 points",
    "Comment \"GUIDE\" and I'll DM it",
    "\"♻️ Repost if this helped\"",
    "Connection request with no note",
    "\"Quick 15 min call?\" in the first DM",
    "Endorsed for a skill you don't have",
    "The 5am routine post",
    "Tagging 12 people who weren't there",
    "\"Unpopular opinion:\" (very popular)",
    "\"Nobody is talking about this\"",
    "\"Let that sink in.\"",
    "\"Read that again.\"",
    "A headline with 5+ pipes",
    "\"Just bumping this up\"",
    "A webinar invite in the DMs",
    "Added to a newsletter you never chose",
    "\"I help X do Y without Z\"",
    "\"Your profile caught my eye\"",
    "\"Hi {FirstName}\"",
    "\"Can I pick your brain?\"",
    "Profile views, zero messages",
    "Liking their own post",
    "Blaming the algorithm",
    "\"Link in the comments 👇\"",
    "Announcing a LinkedIn break (on LinkedIn)",
    "A poll with no real options",
    "A wedding day LinkedIn post",
    "The conference lanyard selfie",
    "\"5 takeaways from [conference]\"",
    "A sad story with a sales CTA",
    "Recruiter DM for the wrong role",
    "A suspiciously smooth AI headshot",
    "A Calendly link in the first message",
    "\"Synergy,\" unironically",
    "A comment that just says \"This.\"",
    "👏 👏 👏 as a whole comment",
    "\"Saving this for later\"",
    "\"10 lessons from 10 years of...\"",
    "\"I got fired. Best day of my life.\"",
    "A leadership lesson from their dog",
    "A stranger on a plane taught them sales",
    "\"Working on something in stealth\"",
    "An \"Insightful\" reaction on a joke",
    "A motivational quote on a sunset",
    "\"Tag someone who needs to hear this\"",
    "\"I don't usually get personal, but...\"",
    "A certificate for a 2 hour course",
    "12 hashtags at the bottom",
    "The crying selfie",
    "A ghostwriting pitch in the DMs",
    "An \"exclusive mastermind\" invite",
    "A voice note DM from a stranger",
    "A carousel with 14 slides",
    "\"Hot take:\" (lukewarm)",
    "The engagement pod swarm",
    "A screenshot of a DM compliment",
    "\"What would you add?\"",
    "\"I rejected a candidate because...\"",
    "\"Hiring is broken\"",
    "A vacation photo with a leadership lesson",
    "\"Stop scrolling.\"",
    "\"Thoughts?\"",
    "Reposting without adding anything",
    "Congrats on a job they left years ago",
    "\"Humbled and honored to share...\""
  ]
};
